refresh_rate = "30 seconds"

[appenders.journey-service]
kind = "rolling_file"
path = "scheduler/scheduler_logs/schedule_output.log"

  [appenders.journey-service.policy]
  kind = "compound"

    [appenders.journey-service.policy.trigger]
    kind = "size"
    limit = "2kb"

    [appenders.journey-service.policy.roller]
    kind = "fixed_window"
    base = 1
    count = 5
    pattern = "scheduler/scheduler_logs/schedule_output_{}.log"

[root]
level = "info"
appenders = [ "journey-service" ]
