[package]
name = "cli_test_msg"
version = "0.1.0"
edition = "2021"

[dependencies]
message_structure = { path = "../../../ex3_shared_libs/message_structure" }
serde_json = "1.0.117"
chrono = "0.4"